#
# This runs when version tag is pushed
#

name: REL

on:
  push:
    tags: ["v[0-9]*"]

jobs:
  sdist:
    name: "Build source package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          pip-install: -r etc/requirements.uv.txt
      - run: uv sync
      - run: make sdist
      - uses: actions/upload-artifact@v7
        with: {name: "dist", path: "dist"}

  publish-github:
    name: "Publish to Github"
    runs-on: ubuntu-latest
    needs: [sdist]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          pip-install: -r etc/requirements.uv.txt

      - name: "Get files"
        uses: actions/download-artifact@v8
        with: {name: "dist", path: "dist"}

      - name: "Install pandoc"
        run: |
          sudo -nH apt-get -u -y install pandoc
          pandoc --version

      - name: "Prepare"
        run: |
          PACKAGE=$(uv version | sed 's/ .*//')
          VERSION=$(uv version --short)
          TGZ="${PACKAGE}-${VERSION}.tar.gz"

          # default - gh:release, pypi
          # PRERELEASE -  gh:prerelease, pypi
          # DRAFT - gh:draft,prerelease, testpypi
          PRERELEASE="false"; DRAFT="false"
          case "${VERSION}" in
            *[ab]*|*rc*) PRERELEASE="true";;
            *dev*) PRERELEASE="true"; DRAFT="true";;
          esac

          test "${{github.ref}}" = "refs/tags/v${VERSION}" || { echo "ERR: tag mismatch"; exit 1; }
          test -f "dist/${TGZ}" || { echo "ERR: sdist failed"; exit 1; }
          echo "PACKAGE=${PACKAGE}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TGZ=${TGZ}" >> $GITHUB_ENV
          echo "PRERELEASE=${PRERELEASE}" >> $GITHUB_ENV
          echo "DRAFT=${DRAFT}" >> $GITHUB_ENV
          mkdir -p tmp
          make -s shownote > tmp/note.md
          cat tmp/note.md
          ls -l dist

      - name: "Create Github release"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          title="${PACKAGE} v${VERSION}"
          ghf="--notes-file=./tmp/note.md"
          if test "${DRAFT}" = "true"; then ghf="${ghf} --draft"; fi
          if test "${PRERELEASE}" = "true"; then ghf="${ghf} --prerelease"; fi
          gh release create "v${VERSION}" "dist/${TGZ}" --title="${title}" ${ghf}

  publish-pypi:
    if: ${{ !contains(github.ref_name, '.dev') }}
    name: "Publish to PyPi"
    runs-on: ubuntu-latest
    needs: [sdist]
    permissions:
      id-token: write
    environment: pypi
    steps:
      - uses: actions/download-artifact@v8
        with: {name: "dist", path: "dist"}
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

  publish-testpypi:
    if: ${{ contains(github.ref_name, '.dev') }}
    name: "Publish to TestPyPi"
    runs-on: ubuntu-latest
    needs: [sdist]
    permissions:
      id-token: write
    environment: testpypi
    steps:
      - uses: actions/download-artifact@v8
        with: { name: "dist", path: "dist" }
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with: { repository-url: "https://test.pypi.org/legacy/" }


